# Generated by Django 5.0.3 on 2024-03-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='product.warehouse')),
                ('mato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mato', to='product.warehouse')),
                ('tugma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugma', to='product.warehouse')),
                ('zamok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamok', to='product.warehouse')),
            ],
        ),
    ]
