# Generated by Django 5.0.3 on 2024-03-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tugma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tugma', to='product.warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zamok',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='zamok', to='product.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
